### ISSUE TITLE
Commands for bot not found

### ISSUE THREAD

**Issue by DSlayer00** [dishapatel010/mmbot#2]
Commands for bot is not found. No response from bot if /help is used or even if used command from the command.py file. For eg. /gplk <gplink>

**Comment by dishapatel010** [comment]
> Commands for bot is not found. No response from bot if /help is used or even if used command from the command.py file. For eg. /gplk

Their are only [This](https://github.com/dishapatel010/mmbot/blob/main/README.md#botfather-setcommands) listed & valid commands
